platform :ios, '11.0'

target 'bidappPlayground' do
  use_frameworks!

  ### canonical pod 'bidapp' will install all available adapters
  pod 'bidapp/SDK'
  
  ### for conrol over installed adapters, comment pod 'bidapp'
  ### and uncomment adapters that you would like to use in project
  pod 'bidapp/Applovin'
  pod 'bidapp/ApplovinMax'
  pod 'bidapp/Unity'
  pod 'bidapp/Liftoff'
  pod 'bidapp/Chartboost'
  pod 'bidapp/AdMob'
  pod 'bidapp/Facebook'
  #pod 'bidapp/Fyber'
  pod 'bidapp/StartApp'
end
