platform :ios, '12.0'

target 'bidappPlayground' do
  use_frameworks!

  pod 'bidapp/Applovin'
  pod 'bidapp/ApplovinMax'
  pod 'bidapp/Unity'
  pod 'bidapp/Liftoff'
  pod 'bidapp/Chartboost'
  pod 'bidapp/AdMob'
  pod 'bidapp/Facebook'
  pod 'bidapp/Fyber'
  pod 'bidapp/StartApp'
  pod 'bidapp/Facebook'
end
